##version: '3.8'
# All composed well, this is milestone so I called i v0.2
services:
  database:
    build:
      # images: radapp_postgres
      context: ./database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ} # Dynamically set timezone based on host
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:z
      - ./etc/localtime:/etc/localtime:ro
    networks:
      custom_network:
        ipv4_address: 10.9.77.2
    healthcheck:                   # Add this section
      test: ["CMD-SHELL", "pg_isready -U radius"]  # Checks if PostgreSQL is ready
      interval: 10s                # Check every 10 seconds
      timeout: 5s                  # Timeout for each check
      retries: 5                   # Retry up to 5 times before marking unhealthy

  radius:
    build:
      context: ./radius_etc
    environment:
      TZ: ${TZ}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
      - "3799:3799/udp"
    volumes:
      - ./etc/localtime:/etc/localtime:ro
    depends_on:
      database:
        condition: service_healthy
    networks:
      custom_network:
        ipv4_address: 10.9.77.3
    command: ["/usr/sbin/freeradius", "-X"]

  backend:
    build:
      # images: radapp_nodejs
      context: ./backend  # Directory containing your Node.js app and Dockerfile
      args:
        - HOST_IP=${HOST_IP}
    ports:
      - "5010:5000"       # Node.js app port exposed
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      HOST_IP: ${HOST_IP}
      # TZ: ${TZ} # Dynamically set timezone based on host
    depends_on:
      - database           # Ensure database container starts first
    networks:
      custom_network:
        ipv4_address: 10.9.77.4
    volumes:
      - ./etc/localtime:/etc/localtime:ro
     # - /var/lib/docker/volumes/ftpdata/_data/myapp/radiusapp_backend_persistent/:/app #temp for devel
    #   - ./backend/hostip.sh:/usr/local/bin/hostip.sh
    # command:
    #   - /bin/bash -c "source /usr/local/bin/hostip.sh"

  adminer:
    image: adminer:latest
    environment:
      - ADMINER_DEFAULT_SERVER=database
      # - TZ=${TZ} # Dynamically set timezone based on host
    ports:
      - "8082:8080"  # Adminer accessible at localhost:8081
    depends_on:
      - database
    networks:
      custom_network:
        ipv4_address: 10.9.77.5
    volumes:
      - /etc/localtime:/etc/localtime:ro

  radapi:
    build:
      context: ./api
    depends_on:
      - database
    command: >
      sh -c "uvicorn api:app --host 0.0.0.0 --port 8000"
    ports:
      - "8077:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      API_KEY: ${API_KEY:?API_KEY is required}
    networks:
      custom_network:
        ipv4_address: 10.9.77.6

networks:
  custom_network:
    ipam:
      config:
        - subnet: 10.9.77.0/24
  # default:
  #   external:
  #     name: host
volumes:
  pgdata:
#   - radius327:
