##version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: radius
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: radius
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      custom_network:
        ipv4_address: 192.168.1.2

  radius:
    image: freeradius/freeradius-server:3.2.7
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
      - "3799:3799/udp"
    volumes:
      - ./radius_etc/_data/:/etc/freeradius
    depends_on:
      - database
    networks:
      custom_network:
        ipv4_address: 192.168.1.3
    #command: ["/usr/sbin/freeradius", "-X"]

  backend:
    build:
      context: ./backend  # Directory containing your Node.js app and Dockerfile
    ports:
      - "5000:5000"       # Node.js app port exposed
    environment:
      DB_HOST: database   # Hostname for database service
      DB_PORT: 5432       # PostgreSQL default port
      DB_USER: radius     # Match the database environment variables
      DB_PASSWORD: 1234
      DB_NAME: radius
    depends_on:
      - database           # Ensure database container starts first
    networks:
      custom_network:
        ipv4_address: 192.168.1.4

  adminer:
    image: adminer:latest
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DEFAULT_SYSTEM=PostgreSQL	
    ports:
      - "8082:8080"  # Adminer accessible at localhost:8081
    depends_on:
      - database
    networks:
      custom_network:
        ipv4_address: 192.168.1.5

networks:
  custom_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24
# volumes:
#   - radius327:
